
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '45802EEEB5577CC54888B47F1D176FD3'
    
_lr_action_items = {'INT':([0,4,],[1,1,]),'ADD':([1,2,5,],[-3,4,4,]),'$end':([1,2,3,5,],[-3,-1,0,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,],[2,5,]),'module':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> expr','module',1,'p_module','example.py',14),
  ('expr -> expr ADD expr','expr',3,'p_expr','example.py',17),
  ('expr -> INT','expr',1,'p_expr','example.py',18),
]
